Repository VLK-STUDIO/catalyst-cms, pull requests merged in 2023-05, with the labels that each got.

#24 fix: reference fields preview
  packages/catalyst/src/data/index.ts
  packages/catalyst/src/data/types.ts
  packages/catalyst/src/ui/components/form/Form.tsx
  packages/catalyst/src/ui/components/form/RichTextInput.tsx
  packages/catalyst/src/ui/components/form/types.ts
  packages/catalyst/src/ui/components/form/utils.ts
  packages/catalyst/src/ui/pages/browse.tsx
  packages/catalyst/src/ui/pages/create.tsx
  packages/catalyst/src/ui/pages/editCollection.tsx
  packages/catalyst/src/ui/pages/editGlobal.tsx
  packages/catalyst/src/ui/pages/utils.ts
  packages/catalyst/src/ui/uno.css
  packages/catalyst/src/utils.ts
Labels: bug

#27 chore: update readme
  README.md
Labels: documentation

#32 fix: reference select input
  examples/blog/src/app/(site)/layout.tsx
  examples/blog/src/app/(site)/page.tsx
  examples/blog/src/app/catalyst/layout.tsx
  packages/catalyst/src/ui/components/form/Form.tsx
  packages/catalyst/src/ui/components/form/FormElements.tsx
  packages/catalyst/src/ui/components/form/SelectInput.tsx
  packages/catalyst/src/ui/pages/browse.tsx
  packages/catalyst/src/ui/pages/utils.ts
Labels: bug

#36 chore(core): Added prettier and its scripts and config
  .prettierrc
  examples/blog/postcss.config.js
  examples/blog/src/cms.ts
  package.json
  packages/catalyst/src/auth.ts
  packages/catalyst/src/data/index.ts
  packages/catalyst/src/data/types.ts
  packages/catalyst/src/endpoints/collectionEntryCreation.ts
  packages/catalyst/src/endpoints/collectionEntryUpdate.ts
  packages/catalyst/src/endpoints/globalUpsert.ts
  packages/catalyst/src/endpoints/index.ts
  packages/catalyst/src/index.ts
  packages/catalyst/src/types.ts
  packages/catalyst/src/ui/pages/utils.ts
  packages/catalyst/src/uno.config.ts
  pnpm-lock.yaml
Labels: enhancement

#50 chore(ex-blog): add seeds
  examples/blog/next.config.js
  examples/blog/package.json
  examples/blog/src/cms.ts
  packages/catalyst/src/config.ts
  packages/catalyst/src/index.ts
  packages/catalyst/src/logger.ts
  packages/catalyst/src/seed.ts
Labels: enhancement

#53 chore: cleanup dashboard (router and folder structure)
  .gitignore
  packages/catalyst/package.json
  packages/catalyst/src/config.ts
  packages/catalyst/src/dashboard/components/Button.tsx
  packages/catalyst/src/dashboard/components/CurrentSubrouteLink.tsx
  packages/catalyst/src/dashboard/components/LivePreviewFrame.tsx
  packages/catalyst/src/dashboard/components/LocaleSwitch.tsx
  packages/catalyst/src/dashboard/components/Logo.tsx
  packages/catalyst/src/dashboard/components/auth/LogoutLoading.tsx
  packages/catalyst/src/dashboard/components/auth/SignInWIthGoogle.tsx
  packages/catalyst/src/dashboard/components/browse/TableBody.tsx
  packages/catalyst/src/dashboard/components/form/Form.tsx
  packages/catalyst/src/dashboard/components/form/FormElements.tsx
  packages/catalyst/src/dashboard/components/form/RichTextInput.tsx
  packages/catalyst/src/dashboard/components/form/SelectInput.tsx
  packages/catalyst/src/dashboard/components/form/TextInput.tsx
  packages/catalyst/src/dashboard/components/form/types.ts
  packages/catalyst/src/dashboard/components/form/utils.ts
  packages/catalyst/src/dashboard/hooks/useDebounce.tsx
  packages/catalyst/src/dashboard/hooks/useFirstSubroute.tsx
  packages/catalyst/src/dashboard/index.tsx
  packages/catalyst/src/dashboard/routes/browse.tsx
  packages/catalyst/src/dashboard/routes/create.tsx
  packages/catalyst/src/dashboard/routes/editCollection.tsx
  packages/catalyst/src/dashboard/routes/editGlobal.tsx
  packages/catalyst/src/dashboard/routes/forbidden.tsx
  packages/catalyst/src/dashboard/routes/index.tsx
  packages/catalyst/src/dashboard/routes/login.tsx
  packages/catalyst/src/dashboard/routes/logout.tsx
  packages/catalyst/src/dashboard/routes/types.ts
  packages/catalyst/src/dashboard/utils.ts
  packages/catalyst/src/data/index.ts
  packages/catalyst/src/data/types.ts
  packages/catalyst/src/types.ts
  packages/catalyst/src/ui/pages/base.tsx
  packages/catalyst/src/ui/pages/browse.tsx
  packages/catalyst/src/ui/pages/editCollection.tsx
  packages/catalyst/src/ui/pages/editGlobal.tsx
  packages/catalyst/src/ui/uno.css
  pnpm-lock.yaml
  turbo.json
Labels: enhancement

#55 chore: move to tailwind for dashboard ui
  examples/blog/.eslintrc.json
  examples/blog/package.json
  packages/catalyst/package.json
  packages/catalyst/tailwind.config.js
  pnpm-lock.yaml
Labels: enhancement

#63 chore: solidify authentication logic
  examples/blog/src/cms.ts
  packages/catalyst/package.json
  packages/catalyst/src/auth.ts
  packages/catalyst/src/config.ts
  packages/catalyst/src/data/index.ts
  packages/catalyst/src/endpoints/globalUpsert.ts
  packages/catalyst/src/endpoints/index.ts
  packages/catalyst/src/index.ts
  packages/catalyst/src/seed.ts
  packages/catalyst/src/types.ts
  pnpm-lock.yaml
Labels: enhancement

#65 chore(ex-blog): added seeding scripts
  .github/workflows/build-blog.yml
  examples/blog/package.json
  examples/blog/scripts/seed.ts
  examples/blog/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement

#67 feat: form loading states and dashboard folder refactor
  packages/catalyst/src/dashboard/components/_shared/Button.tsx
  packages/catalyst/src/dashboard/components/_shared/CurrentSubrouteLink.tsx
  packages/catalyst/src/dashboard/components/_shared/Form/Form.tsx
  packages/catalyst/src/dashboard/components/_shared/Form/FormElements.tsx
  packages/catalyst/src/dashboard/components/_shared/Form/LivePreviewFrame.tsx
  packages/catalyst/src/dashboard/components/_shared/Form/LocaleSwitch.tsx
  packages/catalyst/src/dashboard/components/_shared/Form/RichTextInput.tsx
  packages/catalyst/src/dashboard/components/_shared/Form/SelectInput.tsx
  packages/catalyst/src/dashboard/components/_shared/Form/TextInput.tsx
  packages/catalyst/src/dashboard/components/_shared/Form/index.ts
  packages/catalyst/src/dashboard/components/_shared/Form/types.ts
  packages/catalyst/src/dashboard/components/_shared/Form/utils.ts
  packages/catalyst/src/dashboard/components/_shared/Logo.tsx
  packages/catalyst/src/dashboard/components/_shared/Spinner.tsx
  packages/catalyst/src/dashboard/components/_shared/Toast/Toast.tsx
  packages/catalyst/src/dashboard/components/_shared/Toast/ToastProvider.tsx
  packages/catalyst/src/dashboard/components/_shared/Toast/index.ts
  packages/catalyst/src/dashboard/components/_shared/Toast/types.ts
  packages/catalyst/src/dashboard/components/browse/TableBody.tsx
  packages/catalyst/src/dashboard/components/login/SignInWIthGoogle.tsx
  packages/catalyst/src/dashboard/components/logout/LogoutLoading.tsx
  packages/catalyst/src/dashboard/hooks/useToast.tsx
  packages/catalyst/src/dashboard/index.tsx
  packages/catalyst/src/dashboard/routes/browse.tsx
  packages/catalyst/src/dashboard/routes/create.tsx
  packages/catalyst/src/dashboard/routes/editCollection.tsx
  packages/catalyst/src/dashboard/routes/editGlobal.tsx
  packages/catalyst/src/dashboard/routes/forbidden.tsx
  packages/catalyst/src/dashboard/routes/index.tsx
  packages/catalyst/src/dashboard/routes/login.tsx
  packages/catalyst/src/dashboard/routes/logout.tsx
  packages/catalyst/src/dashboard/utils.ts
Labels: enhancement

#72 feat: optional fields and validation
  examples/blog/src/cms.ts
  packages/catalyst/src/dashboard/components/_shared/Form/Form.tsx
  packages/catalyst/src/dashboard/components/_shared/Form/FormElements.tsx
  packages/catalyst/src/dashboard/components/_shared/Form/TextInput.tsx
  packages/catalyst/src/dashboard/components/_shared/Toast/Toast.tsx
  packages/catalyst/src/dashboard/hooks/useToast.tsx
  packages/catalyst/src/data/types.ts
  packages/catalyst/src/endpoints/collectionEntryCreation.ts
  packages/catalyst/src/endpoints/collectionEntryUpdate.ts
  packages/catalyst/src/endpoints/globalUpsert.ts
  packages/catalyst/src/endpoints/utils.ts
  packages/catalyst/src/types.ts
Labels: enhancement

#73 feat(core): server actions 🫨
  examples/blog/.eslintrc.json
  examples/blog/next.config.js
  examples/blog/src/app/(site)/[slug]/page.tsx
  examples/blog/src/app/(site)/page.tsx
  packages/catalyst/package.json
  packages/catalyst/src/access.ts
  packages/catalyst/src/config.ts
  packages/catalyst/src/dashboard/routes/index.tsx
  packages/catalyst/src/data/actions.ts
  packages/catalyst/src/data/index.ts
  packages/catalyst/src/data/queries.ts
  packages/catalyst/src/data/types.ts
  packages/catalyst/src/data/utils.ts
  packages/catalyst/src/endpoint.ts
  packages/catalyst/src/endpoints/collectionEntryCreation.ts
  packages/catalyst/src/endpoints/collectionEntryUpdate.ts
  packages/catalyst/src/endpoints/globalUpsert.ts
  packages/catalyst/src/endpoints/index.ts
  packages/catalyst/src/endpoints/utils.ts
  packages/catalyst/src/index.ts
  packages/catalyst/src/types.ts
  packages/catalyst/src/ui/components/_shared/Button.tsx
  packages/catalyst/src/ui/components/_shared/CurrentSubrouteLink.tsx
  packages/catalyst/src/ui/components/_shared/Form/Form.tsx
  packages/catalyst/src/ui/components/_shared/Form/FormElements.tsx
  packages/catalyst/src/ui/components/_shared/Form/LivePreviewFrame.tsx
  packages/catalyst/src/ui/components/_shared/Form/LocaleSwitch.tsx
  packages/catalyst/src/ui/components/_shared/Form/RichTextInput.tsx
  packages/catalyst/src/ui/components/_shared/Form/SelectInput.tsx
  packages/catalyst/src/ui/components/_shared/Form/TextInput.tsx
  packages/catalyst/src/ui/components/_shared/Form/index.ts
  packages/catalyst/src/ui/components/_shared/Form/types.ts
  packages/catalyst/src/ui/components/_shared/Form/utils.ts
  packages/catalyst/src/ui/components/_shared/Logo.tsx
  packages/catalyst/src/ui/components/_shared/Spinner.tsx
  packages/catalyst/src/ui/components/_shared/Toast/Toast.tsx
  packages/catalyst/src/ui/components/_shared/Toast/ToastProvider.tsx
  packages/catalyst/src/ui/components/_shared/Toast/index.ts
  packages/catalyst/src/ui/components/_shared/Toast/types.ts
  packages/catalyst/src/ui/components/browse/TableBody.tsx
  packages/catalyst/src/ui/components/browse/TableHead.tsx
  packages/catalyst/src/ui/components/login/SignInWIthGoogle.tsx
  packages/catalyst/src/ui/components/logout/LogoutLoading.tsx
  packages/catalyst/src/ui/hooks/useDebounce.tsx
  packages/catalyst/src/ui/hooks/useFirstSubroute.tsx
  packages/catalyst/src/ui/hooks/useToast.tsx
  packages/catalyst/src/ui/index.tsx
  packages/catalyst/src/ui/routes/browse.tsx
  packages/catalyst/src/ui/routes/create.tsx
  packages/catalyst/src/ui/routes/editCollection.tsx
  packages/catalyst/src/ui/routes/editGlobal.tsx
  packages/catalyst/src/ui/routes/forbidden.tsx
  packages/catalyst/src/ui/routes/index/DataTypeCard.tsx
  packages/catalyst/src/ui/routes/index/index.ts
  packages/catalyst/src/ui/routes/index/route.tsx
  packages/catalyst/src/ui/routes/login.tsx
  packages/catalyst/src/ui/routes/logout.tsx
  packages/catalyst/src/ui/routes/types.ts
  packages/catalyst/src/ui/utils.ts
  packages/catalyst/src/utils.ts
Labels: enhancement
